# Generated by Django 5.2.3 on 2025-07-03 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
