# Generated by Django 5.2.3 on 2025-07-03 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_author_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='company',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='author',
            name='job_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
