# Generated by Django 5.2.3 on 2025-07-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_author_company_author_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
    ]
