# Generated by Django 5.2.3 on 2025-07-09 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_comment_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
