# Generated by Django 5.2.3 on 2025-07-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_author_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MMPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video_id', models.CharField(max_length=32)),
                ('playlist_url', models.URLField()),
                ('duration', models.CharField(max_length=50)),
            ],
        ),
    ]
