# Generated by Django 5.2.3 on 2025-07-11 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_mmplaylist'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeLab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('platform', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('description', models.TextField()),
                ('difficulty', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
