# Generated by Django 5.2.3 on 2025-07-11 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_freelab'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video_id', models.CharField(max_length=50)),
                ('playlist_url', models.URLField()),
                ('channel', models.CharField(blank=True, max_length=100)),
                ('difficulty', models.CharField(blank=True, max_length=20)),
                ('duration', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
