# Generated by Django 5.2.3 on 2025-07-11 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='UdemyCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField()),
                ('author', models.CharField(max_length=255)),
                ('rating', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
