# Generated by Django 5.2.3 on 2025-07-11 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_udemycourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='udemycourse',
            name='author_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
