# Generated by Django 5.2.3 on 2025-07-14 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_udemycourse_author_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='read_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
