# Generated by Django 5.2.3 on 2025-07-16 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_alter_article_slug_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='is_burmese',
            field=models.BooleanField(default=False),
        ),
    ]
