# Generated by Django 5.2.3 on 2025-07-17 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_testimonial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='is_positive',
        ),
    ]
